"""create credit assessments table

Revision ID: 0ce1a8202be7
Revises: 8811b6419be1
Create Date: 2026-09-25 19:31:21.580625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce1a8202be7'
down_revision: Union[str, Sequence[str], None] = '8811b6419be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bureau_score', sa.Integer(), nullable=True),
    sa.Column('score_type', sa.String(length=50), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('active_accounts', sa.Integer(), nullable=True),
    sa.Column('delinquent_accounts', sa.Integer(), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recent_inquiries', sa.Integer(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_report_version', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_assessments_loan_application_id', 'credit_assessments', ['loan_application_id'], unique=False)
    op.create_index('ix_credit_assessments_status', 'credit_assessments', ['status'], unique=False)
    op.create_index('ix_credit_assessments_user_id', 'credit_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_assessments_user_id', table_name='credit_assessments')
    op.drop_index('ix_credit_assessments_status', table_name='credit_assessments')
    op.drop_index('ix_credit_assessments_loan_application_id', table_name='credit_assessments')
    op.drop_table('credit_assessments')
    # ### end Alembic commands ###
