"""add document family versioning

Revision ID: 23dea46aae43
Revises: 58afe180e47c
Create Date: 2026-09-23 01:07:49.432633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23dea46aae43'
down_revision: Union[str, Sequence[str], None] = '58afe180e47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "documents",
        sa.Column(
            "document_family_id",
            sa.UUID(),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE documents
        SET document_family_id = id
        WHERE document_family_id IS NULL
        """
    )

    op.alter_column(
        "documents",
        "document_family_id",
        nullable=False,
    )

    op.create_index(
        op.f("ix_documents_document_family_id"),
        "documents",
        ["document_family_id"],
        unique=False,
    )

    op.create_unique_constraint(
        "uq_documents_family_version",
        "documents",
        ["document_family_id", "version"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_family_version', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_document_family_id'), table_name='documents')
    op.drop_column('documents', 'document_family_id')
    # ### end Alembic commands ###
