"""create policy persistence tables

Revision ID: 3b41c049ca39
Revises: 7d1f6b2a9c40
Create Date: 2026-09-28 22:16:41.950182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b41c049ca39'
down_revision: Union[str, Sequence[str], None] = '7d1f6b2a9c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('ix_policy_versions_effective_from', 'policy_versions', ['effective_from'], unique=False)
    op.create_index('ix_policy_versions_effective_to', 'policy_versions', ['effective_to'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('rule_order', sa.Integer(), nullable=False),
    sa.Column('effect', sa.String(length=50), nullable=False),
    sa.Column(
    'condition',
    postgresql.JSONB(astext_type=sa.Text()),
    nullable=False,
    ),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
    ['policy_version_id'],
    ['policy_versions.id'],
    ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
    'policy_version_id',
    'code',
    name='uq_policy_rules_policy_version_code',
    ),
    sa.UniqueConstraint(
    'policy_version_id',
    'rule_order',
    name='uq_policy_rules_policy_version_order',
    ),
    )
    op.create_index('ix_policy_rules_policy_version_id', 'policy_rules', ['policy_version_id'], unique=False)
    op.create_index('ix_policy_rules_policy_version_order', 'policy_rules', ['policy_version_id', 'rule_order'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('decision_route', sa.String(length=50), nullable=False),
    sa.Column('matched_rule_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_eligible_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_evaluations_decision_route', 'policy_evaluations', ['decision_route'], unique=False)
    op.create_index('ix_policy_evaluations_evaluated_at', 'policy_evaluations', ['evaluated_at'], unique=False)
    op.create_index('ix_policy_evaluations_loan_application_id', 'policy_evaluations', ['loan_application_id'], unique=False)
    op.create_index('ix_policy_evaluations_policy_version_id', 'policy_evaluations', ['policy_version_id'], unique=False)
    op.create_index('ix_policy_evaluations_user_id', 'policy_evaluations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # policy_evaluations must be removed before policy_versions because
    # it references policy_versions with ON DELETE RESTRICT.
    op.drop_index(
        'ix_policy_evaluations_user_id',
        table_name='policy_evaluations',
    )
    op.drop_index(
        'ix_policy_evaluations_policy_version_id',
        table_name='policy_evaluations',
    )
    op.drop_index(
        'ix_policy_evaluations_loan_application_id',
        table_name='policy_evaluations',
    )
    op.drop_index(
        'ix_policy_evaluations_evaluated_at',
        table_name='policy_evaluations',
    )
    op.drop_index(
        'ix_policy_evaluations_decision_route',
        table_name='policy_evaluations',
    )
    op.drop_table('policy_evaluations')

    # Remove policy rules and their constraints/indexes.
    op.drop_constraint(
        'uq_policy_rules_policy_version_order',
        'policy_rules',
        type_='unique',
    )
    op.drop_constraint(
        'uq_policy_rules_policy_version_code',
        'policy_rules',
        type_='unique',
    )
    op.drop_index(
        'ix_policy_rules_policy_version_order',
        table_name='policy_rules',
    )
    op.drop_index(
        'ix_policy_rules_policy_version_id',
        table_name='policy_rules',
    )
    op.drop_table('policy_rules')

    # Finally remove policy versions.
    op.drop_index(
        'ix_policy_versions_effective_to',
        table_name='policy_versions',
    )
    op.drop_index(
        'ix_policy_versions_effective_from',
        table_name='policy_versions',
    )
    op.drop_table('policy_versions')

    # ### end Alembic commands ###
  
