"""add document integrity constraints

Revision ID: 58afe180e47c
Revises: 9c24800f7ded
Create Date: 2026-09-22 15:51:36.693360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58afe180e47c'
down_revision: Union[str, Sequence[str], None] = '9c24800f7ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_owner_checksum', 'documents', ['owner_type', 'owner_id', 'checksum'])
    op.create_unique_constraint('uq_documents_storage_ref', 'documents', ['storage_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_storage_ref', 'documents', type_='unique')
    op.drop_constraint('uq_documents_owner_checksum', 'documents', type_='unique')
    # ### end Alembic commands ###
