"""create affordability assessments table

Revision ID: 58fabdfb3011
Revises: bf0f0b507a13
Create Date: 2026-09-26 14:34:20.427209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fabdfb3011'
down_revision: Union[str, Sequence[str], None] = 'bf0f0b507a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affordability_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_obligations', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('requested_tenure_days', sa.Integer(), nullable=True),
    sa.Column('disposable_monthly_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('existing_obligation_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_version', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affordability_assessments_created_at', 'affordability_assessments', ['created_at'], unique=False)
    op.create_index('ix_affordability_assessments_loan_application_id', 'affordability_assessments', ['loan_application_id'], unique=False)
    op.create_index('ix_affordability_assessments_status', 'affordability_assessments', ['status'], unique=False)
    op.create_index('ix_affordability_assessments_user_id', 'affordability_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affordability_assessments_user_id', table_name='affordability_assessments')
    op.drop_index('ix_affordability_assessments_status', table_name='affordability_assessments')
    op.drop_index('ix_affordability_assessments_loan_application_id', table_name='affordability_assessments')
    op.drop_index('ix_affordability_assessments_created_at', table_name='affordability_assessments')
    op.drop_table('affordability_assessments')
    # ### end Alembic commands ###
