"""create fraud assessments table

Revision ID: 8231b23b193d
Revises: 0ce1a8202be7
Create Date: 2026-09-25 21:57:58.319836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8231b23b193d'
down_revision: Union[str, Sequence[str], None] = '0ce1a8202be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraud_assessments_loan_application_id', 'fraud_assessments', ['loan_application_id'], unique=False)
    op.create_index('ix_fraud_assessments_status', 'fraud_assessments', ['status'], unique=False)
    op.create_index('ix_fraud_assessments_user_id', 'fraud_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fraud_assessments_user_id', table_name='fraud_assessments')
    op.drop_index('ix_fraud_assessments_status', table_name='fraud_assessments')
    op.drop_index('ix_fraud_assessments_loan_application_id', table_name='fraud_assessments')
    op.drop_table('fraud_assessments')
    # ### end Alembic commands ###
