"""create loan applications tables

Revision ID: 8811b6419be1
Revises: 23dea46aae43
Create Date: 2026-09-24 06:22:06.175618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8811b6419be1'
down_revision: Union[str, Sequence[str], None] = '23dea46aae43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('requested_tenure_days', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_index('ix_loan_applications_created_at', 'loan_applications', ['created_at'], unique=False)
    op.create_index('ix_loan_applications_status', 'loan_applications', ['status'], unique=False)
    op.create_index('ix_loan_applications_user_id', 'loan_applications', ['user_id'], unique=False)
    op.create_table('loan_application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_application_events_application_id', 'loan_application_events', ['application_id'], unique=False)
    op.create_index('ix_loan_application_events_created_at', 'loan_application_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_application_events_created_at', table_name='loan_application_events')
    op.drop_index('ix_loan_application_events_application_id', table_name='loan_application_events')
    op.drop_table('loan_application_events')
    op.drop_index('ix_loan_applications_user_id', table_name='loan_applications')
    op.drop_index('ix_loan_applications_status', table_name='loan_applications')
    op.drop_index('ix_loan_applications_created_at', table_name='loan_applications')
    op.drop_table('loan_applications')
    # ### end Alembic commands ###
