"""extend audit logs for immutable audit trail

Revision ID: 9534e9d8830a
Revises: d0e20dacca8f
Create Date: 2026-10-07 02:32:07.542847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9534e9d8830a'
down_revision: Union[str, Sequence[str], None] = 'd0e20dacca8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.JSON(), nullable=True))
   
def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'actor_role')
    # ### end Alembic commands ###
