"""add session device metadata

Revision ID: bdf79e8e75cf
Revises: 41fd169751a4
Create Date: 2026-09-17 17:25:58.538526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdf79e8e75cf'
down_revision: Union[str, Sequence[str], None] = '41fd169751a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_name', sa.String(length=100), nullable=True))
    op.add_column('user_sessions', sa.Column('device_type', sa.String(length=30), nullable=True))
    op.add_column('user_sessions', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'device_type')
    op.drop_column('user_sessions', 'device_name')
    # ### end Alembic commands ###
