"""add fraud provider reference uniqueness

Revision ID: bf0f0b507a13
Revises: bfd18c791663
Create Date: 2026-09-26 04:02:01.738088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0f0b507a13'
down_revision: Union[str, Sequence[str], None] = 'bfd18c791663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_fraud_assessments_provider_reference', 'fraud_assessments', ['provider', 'provider_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fraud_assessments_provider_reference', 'fraud_assessments', type_='unique')
    # ### end Alembic commands ###
