"""split access and refresh tokens

Revision ID: c77464bb70e0
Revises: 7256fea8b85d
Create Date: 2026-09-14 22:44:16.893320

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c77464bb70e0'
down_revision: str | Sequence[str] | None = '7256fea8b85d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "user_sessions",
        sa.Column(
            "access_token_hash",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        "user_sessions",
        sa.Column(
            "refresh_token_hash",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        "user_sessions",
        sa.Column(
            "access_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "user_sessions",
        sa.Column(
            "refresh_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Old sessions cannot be migrated because we only stored
    # the old token hash, not the original token.
    # They will therefore be invalidated by removing the old
    # token columns below.

    op.drop_constraint(
        op.f("user_sessions_token_hash_key"),
        "user_sessions",
        type_="unique",
    )

    op.drop_column("user_sessions", "expires_at")
    op.drop_column("user_sessions", "token_hash")

    op.alter_column(
        "user_sessions",
        "access_token_hash",
        nullable=False,
    )

    op.alter_column(
        "user_sessions",
        "refresh_token_hash",
        nullable=False,
    )

    op.alter_column(
        "user_sessions",
        "access_token_expires_at",
        nullable=False,
    )

    op.alter_column(
        "user_sessions",
        "refresh_token_expires_at",
        nullable=False,
    )

    op.create_unique_constraint(
        "uq_user_sessions_access_token_hash",
        "user_sessions",
        ["access_token_hash"],
    )

    op.create_unique_constraint(
        "uq_user_sessions_refresh_token_hash",
        "user_sessions",
        ["refresh_token_hash"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_sessions_access_token_hash', 'user_sessions', type_='unique')
    op.drop_constraint('uq_user_sessions_refresh_token_hash', 'user_sessions', type_='unique')
    op.create_unique_constraint(op.f('user_sessions_token_hash_key'), 'user_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_sessions', 'refresh_token_expires_at')
    op.drop_column('user_sessions', 'access_token_expires_at')
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.drop_column('user_sessions', 'access_token_hash')
    # ### end Alembic commands ###
